apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service-deployment
  labels:
    app: cache-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
      - name: cache-service
        image: sobrian.azurecr.io/cache-service
        ports:
        - containerPort: 8080
--
apiVersion: v1
kind: Service
metadata:
  name: cache-service-service
spec:
  selector:
    app: cache-service
  type: LoadBalancer
  ports:
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 8080